version: '3.1'

volumes:
    uploads: {}
    db: {}

services:
    mongo:
        image: mongo
        expose:
            - "27017"
        restart: unless-stopped
        volumes:
            - db:/data/db

    platform:
        build: .
        restart: unless-stopped
        environment:
            - NODE_OPTIONS=--max_old_space_size=2048
            - REGISTER_CODE=1234
        depends_on:
            - 'mongo'
        ports:
            - "3000:3000"
        volumes:
            - uploads:/app/uploads

    squib:
        build:
            context: src/docker/squib
            dockerfile: Dockerfile
        expose:
            - "3001"
        volumes:
            - uploads:/root/work/uploads
        restart: unless-stopped

    nginx:
        build: src/docker/nginx
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            - platform
        volumes:
            - uploads:/var/www/platform/uploads