version: '3.1'

# Docker compose file for development.

volumes:
    db: { }
    uploads: { }
    sessions: { }

services:
    mongo:
        image: mongo
        command: --wiredTigerCacheSizeGB 0.5
        expose:
            - "27017"
        restart: unless-stopped
        volumes:
            - db:/data/db

    server:
        build:
            context: .
            dockerfile: dev.Dockerfile
        env_file:
            - server.env
            - server.env.local
        environment:
            - NODE_OPTIONS=--max_old_space_size=2048
        restart: unless-stopped
        depends_on:
            - 'mongo'
        ports:
            - "3000:3000"
            - "10000:10000"
            - "24678:24678"
        volumes:
            - ./src:/app/src/:consistent
            - ./static:/app/static/:ro
            - uploads:/app/uploads
            - sessions:/app/sessions
            - uploads:/app/static/uploads/:ro

    prod:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - server.env
            - server.env.local
        restart: unless-stopped
        depends_on:
            - 'mongo'
        ports:
            - "3000:3000"
        volumes:
            - uploads:/app/uploads
            # Note, /uploads/... needs to be served - see nginx

    squib:
        build:
            context: workers/squib
            dockerfile: Dockerfile
        ports:
            - 3001
        volumes:
            - uploads:/root/work/uploads
        restart: unless-stopped

    nginx:
        image: nginx
        volumes: 
          - ./nginx/templates:/etc/nginx/templates
          - uploads:/usr/share/nginx/cardographer2/uploads
        ports: 
          - 8080:80

